server.port: 8080

spring.application.name: gateway

ribbon.ServerListRefreshInterval: 5000
ribbon.NFLoadBalancerPingInterval: 5

spring.cloud.gateway.routes:

  - id: legacy-customer-error
    uri: http://legacy-customer
    predicates:
      - Path=/customer-error
    filters:
      - RewritePath=/customer-error, /swing/api/v1/customers/exception

  - id: legacy-customer
    uri: http://legacy-customer
    predicates:
      - Path=/legacy-customer/**
    filters:
      - RewritePath=/legacy-customer/(?<path>.*),/$\{path}

  - id: composite
    uri: http://frontend
    predicates:
      - Path=/composite/**
    filters:
      - RewritePath=/composite/(?<path>.*),/$\{path}

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE

---
spring.profiles: docker
