spring:
  jpa:
    show_sql: true
    format_sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect


  datasource:
    initialization-mode: always
    url: jdbc:mysql://mysql-new-customer/customer-b
    username: user
    password: pwd
    driver-class-name: com.mysql.cj.jdbc.Driver
    #schema: classpath*:db/mysql/schema.sql
